nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] # Cambia por la URL de tu frontend
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'auth-token']
        expose_headers: []
        max_age: 3600
        allow_credentials: true # Permitir cookies, tokens u otras credenciales
    paths:
        '^/api/': # Rutas protegidas por CORS
            allow_origin: ['http://localhost:3000'] # Cambia por la URL de tu frontend
            allow_methods: ['GET', 'POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'auth-token']

            